site_name: 'Página de David Torró'
site_description: 'Esta es mi página creada para la práctica con el tema "material".'
site_author: 'David Torró Bautista'
site_url: https://DavidTorro.github.io/MkDocs/

theme: 
  name: 'material'
  favicon: 'logos_iconos/favIcon.ico'
  logo: 'logos_iconos/logo.png'

  features:
    - content.code.copy  # copiar y pegar los bloques de código
    - content.action.edit  # botón edit
    - content.action.view  # botón view
    - navigation.tabs  # otra vista del menú lateral, en este caso si está activo nos saldrá arriba (horizontal) el menú
    - navigation.tabs.sticky

  palette:
    scheme: 'slate'  # color de fondo
    primary: 'blue'  # color barra superior

nav:
  - Inicio: index.md
  - Perfil Profesional: PerfilProfesional.md
  - Módulos:
      - Base de Datos: BBDD.md
      - Entornos de Desarrollo: Entornos.md
      - Programación: Programación.md
      - Sistemas Informáticos: Sistemas.md
      - Lenguajes de Marca: Lenguajes.md
      - Inglés: Ingles.md
      - Proyecto Intermodular: Proyecto.md

plugins:
  - search  # implementa menú de búsqueda
  - macros  # permite uso de macros

markdown_extensions:
  - admonition
  - toc:  # genera automáticamente una tabla de contenido basada en los encabezados del documento
      permalink: true  # Añade enlaces permanentes
  - codehilite:  # Agrega resaltado de sintaxis al código en Markdown, mejorando la legibilidad
      guess_lang: false  # Si es true, el lenguaje se determina automáticamente, sino lo especificas tú

repo_url: 'https://github.com/DavidTorro/Primera-practica-mkdocs'
repo_name: 'Repositorio de la práctica'
edit_uri: 'edit/main/docs'  # donde se editará al pulsar el botón de edit

use_directory_urls: true  # hace que las URLs generadas por MkDocs omitan el .html al final 
strict: false  # MODO ESTRICTO si tiene warnings no se "compila"
